#! /bin/bash

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

cd OpenImageIO-2.5.7.0
mkdir build
cd build

#cmake .. # how does this not require the installatin prefix?
cmake -DCMAKE_PREFIX_PATH=$REZ_QT_ROOT/6.5.6/gcc_64/lib/cmake/Qt6Gui -DPYTHON_VERSION=$REZ_PYTHON_MAJOR_VERSION.$REZ_PYTHON_MINOR_VERSION -DNuke_ROOT=$NUKE_LOCATION -DOpenJPEG_ROOT=$REZ_OPENJPEG_ROOT -DJPEGTurbo_ROOT=$REZ_LIBJPEGTURBO_ROOT -Dpybind11_ROOT=$REZ_PYBIND11_ROOT -DBOOST_ROOT=$REZ_BOOST_ROOT -DTBB_ROOT=$REZ_TBB_ROOT -DFFmpeg_ROOT=$REZ_FFMPEG_ROOT -DOpenColorIO_ROOT=$REZ_OCIO_ROOT -DOPENEXR_LOCATION=$REZ_OPENEXR_ROOT -DOPENEXR_LIBRARY_DIR=$REZ_OPENEXR_ROOT/lib -DOPENEXR_INCLUDE_DIR=$REZ_OPENEXR_INCLUDE_DIR=$REZ_OPENEXR_ROOT/include -DCMAKE_INSTALL_PREFIX=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION ..

make -j$MAKE_THREADS
make install -j$MAKE_THREADS

cd ../..
cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION
