#! /bin/bash

source version.sh

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

mkdir build

cd build

cmake ../yaml-cpp-$VERSION -DCMAKE_INSTALL_PREFIX=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION -DBUILD_SHARED_LIBS=ON -DCMAKE_CXX_STANDARD=17
make -j$MAKE_THREADS
make install -j$MAKE_THREADS

cd ..

cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION