#! /bin/bash

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

cd oiio-Release-2.1.9.0
mkdir build
cd build

#cmake .. # how does this not require the installatin prefix?
cmake -DCMAKE_PREFIX_PATH=$REZ_QT_ROOT/5.6/gcc_64/lib/cmake/Qt5Gui -DBOOST_ROOT=$REZ_BOOST_ROOT -DOpenColorIO_ROOT=$REZ_OCIO_ROOT -DOPENEXR_LOCATION=$REZ_OPENEXR_ROOT -DOPENEXR_LIBRARY_DIR=$REZ_OPENEXR_ROOT/lib -DOPENEXR_INCLUDE_DIR=$REZ_OPENEXR_INCLUDE_DIR=$REZ_OPENEXR_ROOT/include -DCMAKE_INSTALL_PREFIX=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION ..

make -j$MAKE_THREADS
make install -j$MAKE_THREADS

cd ../..
cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION
