#! /bin/bash

source version.sh

# this will build and install the rez package locally (default is ~/packages)

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

mkdir build
cd build

cmake ../blender -DCMAKE_INSTALL_PREFIX=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION -DPYTHON_INCLUDE_DIR=$PYTHON_INCLUDE_DIRS -DFREETYPE_DIR=$REZ_FREETYPE_ROOT -DFREETYPE_INCLUDE_DIRS=$REZ_FREETYPE_ROOT/include -DIMATH_ROOT_DIR=$REZ_IMATH_ROOT -DFFMPEG_ROOT_DIR=$REZ_FFMPEG_ROOT -DOPENEXR_ROOT_DIR=$REZ_OPENEXR_ROOT -DUSD_ROOT_DIR=$REZ_USD_MONOLITHIC_ROOT -DOPENVDB_ROOT_DIR=$REZ_OPENVDB_ROOT -DJEMALLOC_ROOT_DIR=$REZ_JEMALLOC_ROOT -DOPENCOLORIO_ROOT_DIR=$REZ_OCIO_ROOT -DOPENIMAGEIO_ROOT_DIR=$REZ_OIIO_ROOT -DOSL_ROOT_DIR=$REZ_OPENSHADINGLANGUAGE_ROOT -DEMBREE_ROOT_DIR=$REZ_EMBREE_LIB_ROOT -DTBB_ROOT_DIR=$REZ_TBB_ROOT -DFFTW3_ROOT_DIR=$REZ_FFTW_ROOT -DWEBP_ROOT_DIR=$REZ_WEBP_ROOT -DIMATH_ROOT_DIR=$REZ_IMATH_ROOT -DALEMBIC_ROOT_DIR=$REZ_ALEMBIC_ROOT -DOPENPGL_ROOT_DIR=$REZ_OPENPGL_ROOT

make -j$MAKE_THREADS
make install -j$MAKE_THREADS

cd ..

cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION