#! /usr/bin/bash

mkdir $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME
mkdir $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

mkdir OpenSubdiv-3_4_3/build
cd OpenSubdiv-3_4_3/build
cmake -DTBB_LOCATION=$REZ_TBB_ROOT -DTBB_INCLUDE_DIR=$REZ_TBB_ROOT/include -DCMAKE_INSTALL_PREFIX=$PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION ..
make -j$MAKE_THREADS
make install -j$MAKE_THREADS
cd ../..
cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION


