#! /usr/bin/bash

export PACKAGE_INSTALLATION_ROOT=~/packages
export PACKAGE_NAME=ptex
export PACKAGE_VERSION=2.0.37
export MAKE_THREADS=28

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

cd ptex-2.0.37/src
make -j$MAKE_THREADS
cd ../install
cp -r * $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION
cd ../..
cp package.py $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION

# this seems to be necessary, as USD looks for a lib64 dir regardless of $PACKAGE_NAME version
ln -s $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION/lib $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME/$PACKAGE_VERSION/lib64


