#! /bin/bash

export PACKAGE_INSTALoLATION_ROOT=~/packages
export PACKAGE_NAME=tbb
export PACKAGE_VERSION=4.3.1

mkdir -p $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME

mv tbb43_20141023oss 4.3.1
cp package.py $PACKAGE_VERSION
mv $PACKAGE_VERSION $PACKAGE_INSTALLATION_ROOT/$PACKAGE_NAME
